version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/misternegative21/vihang:latest
    container_name: vihang_backend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: vihang_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
